output-format: pylint
strictness: veryhigh

uses:
  - django

ignore-paths:
  - .mypy_cache
  - migrations
  - node_modules
  - venv
  - __pycache__
  - manage.py

mypy:
  run: false

bandit:
  run: true

dodgy:
  run: false

pylint:
  enable:
    - useless-suppression
  options:
    max-line-length: 120
    max-parents: 12
    django-settings-module: SBtools.settings.development

pycodestyle:
  options:
    max-line-length: 120