from datetime import date, datetime, time

__ALL__: list[str]

def parse(input: datetime | time | int | float | str) -> datetime | None: ...
def date_to_datetime(d: date) -> datetime: ...
def time_to_datetime(t: time) -> datetime: ...
def timestamp_to_datetime(ts: float | int) -> datetime: ...
def string_to_data_time(d: str) -> datetime: ...
